// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsD39e7LfC8nyRduchOqix-11HOj3Stak',
    appId: '1:149545695395:web:89399626d86a0a3e59a716',
    messagingSenderId: '149545695395',
    projectId: 'fazaapp-d4a97',
    authDomain: 'fazaapp-d4a97.firebaseapp.com',
    storageBucket: 'fazaapp-d4a97.firebasestorage.app',
    measurementId: 'G-W16N3P2T15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk7HeE6_NSHPqTmOJX4JmBXEX77OR-Nr8',
    appId: '1:149545695395:android:8d68282022bd4ec159a716',
    messagingSenderId: '149545695395',
    projectId: 'fazaapp-d4a97',
    storageBucket: 'fazaapp-d4a97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcrIehm5k4ISWnf9hwOIYnuK6rvxyTcLo',
    appId: '1:149545695395:ios:c970edab303dcf9759a716',
    messagingSenderId: '149545695395',
    projectId: 'fazaapp-d4a97',
    storageBucket: 'fazaapp-d4a97.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcrIehm5k4ISWnf9hwOIYnuK6rvxyTcLo',
    appId: '1:149545695395:ios:c970edab303dcf9759a716',
    messagingSenderId: '149545695395',
    projectId: 'fazaapp-d4a97',
    storageBucket: 'fazaapp-d4a97.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsD39e7LfC8nyRduchOqix-11HOj3Stak',
    appId: '1:149545695395:web:fc2dbc6e7ad617f859a716',
    messagingSenderId: '149545695395',
    projectId: 'fazaapp-d4a97',
    authDomain: 'fazaapp-d4a97.firebaseapp.com',
    storageBucket: 'fazaapp-d4a97.firebasestorage.app',
    measurementId: 'G-7DYYD2Q3D3',
  );
}